# Generated by Django 4.1.3 on 2023-08-03 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGW',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
                ('Card', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CGW',
            },
        ),
        migrations.CreateModel(
            name='cSDE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'cSDE',
            },
        ),
        migrations.CreateModel(
            name='DGW',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
                ('Card', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DGW',
            },
        ),
        migrations.CreateModel(
            name='dSDE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'dSDE',
            },
        ),
        migrations.CreateModel(
            name='IGW',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'IGW',
            },
        ),
        migrations.CreateModel(
            name='MX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MX',
            },
        ),
        migrations.CreateModel(
            name='SIGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SIGR',
            },
        ),
        migrations.CreateModel(
            name='WAS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WAS',
            },
        ),
        migrations.CreateModel(
            name='WGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WGR',
            },
        ),
        migrations.CreateModel(
            name='WPR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WPR',
            },
        ),
        migrations.CreateModel(
            name='WRS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Router_Ports', models.CharField(max_length=100, unique=True)),
                ('Site', models.CharField(max_length=100)),
                ('Router', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Module_Description', models.CharField(max_length=100)),
                ('Port_Name', models.CharField(max_length=100)),
                ('Port_Status', models.CharField(max_length=100)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Negotiated_Speed', models.CharField(blank=True, max_length=100, null=True)),
                ('Bandwidth', models.CharField(max_length=100)),
                ('Optics', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WRS',
            },
        ),
        migrations.CreateModel(
            name='WrsReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.wrs', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WrsReservations',
            },
        ),
        migrations.CreateModel(
            name='WprReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.wpr', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WprReservations',
            },
        ),
        migrations.CreateModel(
            name='WgrReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.wgr', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WgrReservations',
            },
        ),
        migrations.CreateModel(
            name='WasReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.was', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WasReservations',
            },
        ),
        migrations.CreateModel(
            name='SigrReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.sigr', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SigrReservations',
            },
        ),
        migrations.CreateModel(
            name='MxReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.mx', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MxReservations',
            },
        ),
        migrations.CreateModel(
            name='IgwReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.igw', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IgwReservations',
            },
        ),
        migrations.CreateModel(
            name='DsdeReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.dsde', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DsdeReservations',
            },
        ),
        migrations.CreateModel(
            name='DgwReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.dgw', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DgwReservations',
            },
        ),
        migrations.CreateModel(
            name='CsdeReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.csde', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CsdeReservations',
            },
        ),
        migrations.CreateModel(
            name='CgwReservations',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('order_date', models.DateField(db_column='order_date', default=django.utils.timezone.now, verbose_name='Ordered At')),
                ('Router_Ports', models.OneToOneField(db_column='Router_Ports', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.cgw', to_field='Router_Ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CgwReservations',
            },
        ),
    ]
